name: 'Create PR: homol to main'
on:
  push:
    branches:
      - 'homol'
jobs:
  create_pull_request:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 'Check out repository'
        uses: 'actions/checkout@v3'
      - name: 'Check for existing Pull Request'
        id: 'check_pr'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: |
          pr_exists=$(gh pr list --head homol --base main --json number | jq 'length > 0')
          echo "exists=$pr_exists" >> $GITHUB_OUTPUT
      - name: 'Create Pull Request'
        if: "steps.check_pr.outputs.exists == 'false'"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: |
          gh pr create \
            --base main \
            --head homol \
            --title "[Automated] Merge homol into main" \
            --body "This pull request was automatically created."
